import re
word_list = {
'door': 'doorway',
'hand': 'handwriting',
'type': 'typecast',
'landslide': 'landslip',
'pain': 'trouble',
'apples': 'apple',
'town': 'township',
'actor': 'doer',
'climate': 'mood',
'minutes': 'moment',
'aliens': 'stranger',
'animal': 'carnal',
'Candles': 'candle',
'number': 'total',
'math': 'mathematics',
'book': 'script',
'fun': 'playfulness',
'wind': 'scent',
'teeth': 'dentition',
'kinds': 'kind',
'conference': 'league',
'fortune': 'luck',
'percent': 'percentage',
'problems': 'trouble',
'zoo': 'menagerie',
'envy': 'begrudge',
'class': 'course',
'pond': 'pool',
'shoemaker': 'cobbler',
'gold': 'golden',
'problem': 'trouble',
'country': 'nation',
'manager': 'director',
'tons': 'lots',
'oil': 'petroleum',
'plan': 'design',
'top': 'pinch',
'winds': 'wreathe',
'plastic': 'pliant',
'dark': 'night',
'ducks': 'evade',
'handbag': 'purse',
'background': 'setting',
'grumbling': 'rumble',
'city': 'metropolis',
'girlfriends': 'girl',
'storm': 'surprise',
'dogs': 'pawls',
'plenty': 'plenitude',
'hair': 'haircloth',
'win': 'gain',
'delight': 'enjoy',
'flower': 'peak',
'prize': 'trophy',
'kidnapping': 'snatch',
'heart': 'center',
'ability': 'power',
'family': 'syndicate',
'harbor': 'seaport',
'effect': 'impression',
'rent': 'tear',
'dog': 'pawl',
'picture': 'show',
'news': 'newsworthiness',
'race': 'rush',
'hope': 'promise',
'flowers': 'bloom',
'loads': 'warhead',
'cake': 'patty',
'part': 'contribution',
'accident': 'stroke',
'shock': 'traumatize',
'meeting': 'touch',
'field': 'area',
'woman': 'womanhood',
'evening': 'level',
'cat': 'vomit',
'clothes': 'dress',
'ear': 'auricle',
'approval': 'blessing',
'government': 'politics',
'ring': 'band',
'phones': 'telephone',
'ideas': 'theme',
'anger': 'wrath',
'bank': 'deposit',
'skirt': 'surround',
'religion': 'faith',
'neighborhood': 'locality',
'coin': 'mint',
'illness': 'sickness',
'wood': 'woodwind',
'duty': 'tariff',
'bear': 'pay',
'glasses': 'spectacles',
'privacy': 'secrecy',
'arm': 'sleeve',
'music': 'medicine',
'revolution': 'gyration',
'faults': 'error',
'boys': 'son',
'automobiles': 'car',
'homework': 'prep',
'area': 'field',
'rose': 'mount',
'ache': 'suffer',
'speed': 'hurry',
'box': 'package',
'legs': 'stage',
'fantasy': 'illusion',
'mother': 'fuss',
'doom': 'sentence',
'fight': 'oppose',
'fashion': 'way',
'wrist': 'carpus',
'feast': 'banquet',
'quagmire': 'mire',
'watch': 'see',
'checkers': 'checker',
'beauty': 'mantrap',
'scent': 'nose',
'cow': 'overawe',
'perspiration': 'sweating',
'dick': 'gumshoe',
'password': 'watchword',
'village': 'hamlet',
'friends': 'supporter',
'dishonesty': 'knavery',
'experience': 'know',
'regulations': 'rule',
'service': 'servicing',
'games': 'plot',
'light': 'luminosity',
'foot': 'infantry',
'matter': 'subject',
'lemon': 'stinker',
'audience': 'hearing',
'lunatic': 'moonstruck',
'sharp': 'shrill',
'studying': 'contemplate',
'insects': 'worm',
'chest': 'thorax',
'intelligence': 'news',
'report': 'account',
'crowd': 'herd',
'range': 'straddle',
'boy': 'son',
'wound': 'wounding',
'error': 'mistake',
'calculus': 'tartar',
'areas': 'area',
'material': 'corporeal',
'coup': 'takeover',
'languages': 'terminology',
'father': 'founder',
'wallet': 'billfold',
'heroism': 'valor',
'blow': 'waste',
'chocolate': 'cocoa',
'peppers': 'capsicum',
'clay': 'mud',
'fault': 'error',
'carelessness': 'negligence',
'cheeks': 'impudence',
'example': 'model',
'honks': 'vomit',
'cave': 'undermine',
'foreigners': 'outsider',
'century': 'hundred',
'woods': 'woodwind',
'border': 'edge',
'phone': 'telephone',
'intestine': 'gut',
'point': 'sharpen',
'drinks': 'toast',
'parade': 'troop',
'shadows': 'trace',
'valley': 'vale',
'raise': 'lift',
'mammal': 'mammalian',
'gums': 'mumble',
'study': 'survey',
'festival': 'fete',
'province': 'state',
'vacation': 'holiday',
'lip': 'sassing',
'linguistics': 'philology',
'medal': 'decoration',
'clouds': 'swarm',
'week': 'workweek',
'monkey': 'tamper',
'ass': 'fuck',
'danger': 'risk',
'selling': 'marketing',
'bathroom': 'toilet',
'cult': 'furor',
'nut': 'testicle',
'air': 'ventilate',
'laundering': 'wash',
'Fish': 'Pisces',
'pistol': 'handgun',
'movie': 'film',
'branches': 'ramify',
'gift': 'give',
'turkey': 'bomb',
'muffin': 'gem',
'cost': 'price',
'lot': 'band',
'constipation': 'stultification',
'log': 'logarithm',
'behavior': 'demeanor',
'wall': 'palisade',
'medicine': 'medicate',
'candy': 'sugarcoat',
'dike': 'dyke',
'plain': 'bare',
'arsonist': 'incendiary',
'billion': 'million',
'packs': 'pile',
'lips': 'sassing',
'attention': 'care',
'Subway': 'underpass',
'expenditure': 'outgo',
'Wednesday': 'Midweek',
'coat': 'cake',
'pussy': 'purulent',
'newspaper': 'paper',
'desert': 'defect',
'fan': 'winnow',
'lottery': 'drawing',
'voyage': 'navigate',
'extract': 'distill',
'ocean': 'sea',
'friend': 'supporter',
'profits': 'winnings',
'help': 'serve',
'robots': 'automaton',
'daughter': 'girl',
'counterfeit': 'forge',
'venture': 'stake',
'square': 'squarely',
'sun': 'sunlight',
'jump': 'start',
'carp': 'cavil',
'dress': 'preen',
'verse': 'versify',
'cliff': 'drop',
'brother': 'buddy',
'checks': 'see',
'inches': 'edge',
'insult': 'affront',
'mould': 'form',
'hunting': 'search',
'lack': 'miss',
'executions': 'performance',
'cows': 'overawe',
'waist': 'waistline',
'insect': 'worm',
'Earth': 'world',
'metres': 'time',
'husband': 'hubby',
'sweat': 'perspiration',
'names': 'list',
'cakes': 'patty',
'poop': 'stern',
'draw': 'withdraw',
'rats': 'scab',
'pen': 'write',
'kilos': 'kilogram',
'trouble': 'bother',
'prey': 'raven',
'novel': 'refreshing',
'grave': 'sculpt',
'decision': 'decisiveness',
'pigs': 'slob',
'ax': 'axe',
'skin': 'peel',
'overture': 'prelude',
'families': 'syndicate',
'planet': 'satellite',
'pit': 'stone',
'smuggler': 'runner',
'job': 'subcontract',
'man': 'world',
'project': 'protrude',
'chickens': 'wimp',
'swarm': 'teem',
'stream': 'flow',
'sock': 'windsock',
'record': 'enter',
'beans': 'bean',
'data': 'datum',
'dilemma': 'quandary',
'efforts': 'feat',
'midday': 'noon',
'butt': 'target',
'label': 'mark',
'keys': 'winder',
'enemy': 'foe',
'scene': 'view',
'parents': 'raise',
'shooting': 'charge',
'question': 'query',
'court': 'woo',
'nobody': 'cipher',
'life': 'biography',
'records': 'register',
'body': 'torso',
'books': 'script',
'haunt': 'obsess',
'pong': 'niff',
'lots': 'dozens',
'bird': 'fowl',
'pennies': 'cent',
'sport': 'boast',
'piano': 'softly',
'talks': 'speak',
'mistake': 'err',
'shop': 'browse',
'eye': 'eyeball',
'sentence': 'condemn',
'authorities': 'government',
'houses': 'theatre',
'marks': 'target',
'trash': 'junk',
'forces': 'squeeze',
'hunters': 'orion',
'volume': 'loudness',
'lesson': 'moral',
'knives': 'tongue',
'con': 'swindle',
'noon': 'midday',
'pub': 'saloon',
'evidence': 'show',
'petrol': 'gas',
'bath': 'tub',
'brow': 'hilltop',
'burger': 'hamburger',
'pair': 'couple',
'rate': 'value',
'wolves': 'wolf',
'criminal': 'felonious',
'shit': 'defecate',
'penis': 'phallus',
'biscuit': 'cookie',
'moons': 'lunation',
'muscles': 'muscleman',
'garlic': 'ail',
'speeding': 'hurry',
'passport': 'recommendation',
'cheek': 'impudence',
'cereal': 'grain',
'coal': 'ember',
'work': 'workplace',
'chopsticks': 'chopstick',
'paramedics': 'paramedic',
'sand': 'sandpaper',
'doughnuts': 'ring',
'Delegates': 'assign',
'chairperson': 'chairman',
'reply': 'answer',
'guests': 'node',
'crisps': 'wrinkle',
'culture': 'polish',
'snacks': 'nosh',
'chastity': 'virtue',
'exhibit': 'show',
'elderly': 'older',
'thief': 'stealer',
'drug': 'dose',
'berries': 'berry',
'cultures': 'polish',
'turtles': 'turtleneck',
'airport': 'airdrome',
'tag': 'mark',
'sets': 'typeset',
'prisoner': 'captive',
'airplane': 'plane',
'jam': 'pile',
'butterflies': 'flirt',
'chair': 'professorship',
'hawk': 'peddle',
'wool': 'fleece',
'language': 'terminology',
'treaty': 'pact',
'trip': 'travel',
'rush': 'race',
'arrival': 'arriver',
'hares': 'rabbit',
'throng': 'pile',
'assistant': 'help',
'misconduct': 'wrongdoing',
'farewell': 'parting',
'draughts': 'gulp',
'alphabet': 'rudiment',
'squid': 'calamari',
'socializing': 'socialize',
'jaguars': 'panther',
'murderer': 'liquidator',
'battle': 'combat',
'bug': 'tap',
'rooms': 'suite',
'penalty': 'punishment',
'subject': 'theme',
'trade': 'merchandise',
'puppy': 'pup',
'opponent': 'opposition',
'turtle': 'turtleneck',
'badger': 'wisconsinite',
'farming': 'raise',
'piggy': 'piglet',
'socks': 'windsock',
'cooking': 'fudge',
'toast': 'drink',
'chairman': 'president',
'sports': 'sportsman',
'seek': 'try',
'chirps': 'tweedle',
'subway': 'underpass',
'veggie': 'vegetable',
'train': 'rail',
'toad': 'frog',
'sword': 'blade',
'baby': 'coddle',
'soap': 'lather',
'mails': 'send',
'dishcloth': 'dishrag',
'hunter': 'orion',
'jogging': 'trot',
'boxers': 'packer',
'fans': 'winnow',
'bears': 'pay',
'window': 'windowpane',
'wizard': 'sorcerer',
'Cycling': 'motorbike',
'comedy': 'drollery',
'exercise': 'workout',
'Scream': 'yell',
'cloth': 'fabric',
'essay': 'try',
'cattle': 'oxen',
'medley': 'potpourri',
'worms': 'twist',
'diploma': 'sheepskin',
'toss': 'pitch',
'monkeys': 'tamper',
'Somebody': 'person',
'rabbit': 'lapin',
'bullet': 'fastball',
'joke': 'jest',
'guardian': 'defender',
'sweater': 'jumper',
'anthem': 'hymn',
'alarm': 'dismay',
'cab': 'taxi',
'grouch': 'grumble',
'abortion': 'miscarriage',
'destruction': 'end',
'chatter': 'yak',
'congratulations': 'praise',
'cock': 'swagger',
'bar': 'streak',
'offer': 'extend',
'dishes': 'beauty',
'quarrel': 'dispute',
'bull': 'taurus',
'wash': 'lave',
'linguist': 'polyglot',
'hedgehog': 'porcupine',
'bicycle': 'cycle',
'license': 'certify',
'cook': 'fudge',
'disrespect': 'disesteem',
'base': 'basal',
'bully': 'browbeat',
'telephone': 'call',
'credentials': 'certificate',
'firefighters': 'fireman',
'comments': 'remark',
'merchant': 'merchandiser',
'dictionary': 'lexicon',
'luggage': 'baggage',
'pages': 'foliate',
'cap': 'hood',
'jar': 'jarful',
'hippo': 'hippopotamus',
'policeman': 'officer',
'chief': 'headman',
'freeway': 'pike',
'blowtorch': 'torch',
'castle': 'palace',
'liar': 'prevaricator',
'sofa': 'couch',
'documentary': 'objective',
'physician': 'doctor',
'engine': 'locomotive',
'excuse': 'pardon',
'victim': 'dupe',
'lawyer': 'attorney',
'doctor': 'sophisticate',
'cabinet': 'console',
'beggar': 'pauperize',
'marine': 'nautical',
'account': 'report',
'brutes': 'brute',
'talk': 'speak',
'conundrum': 'riddle',
'award': 'prize',
'knife': 'stab',
'typos': 'misprint',
'student': 'pupil',
'expressway': 'freeway',
'nonsense': 'nonsensical',
'taxi': 'cab',
'acquaintance': 'friend',
'bracelet': 'watchband',
'stage': 'present',
'boxer': 'packer',
'hall': 'manse',
'bike': 'motorcycle',
'blackboard': 'chalkboard',
'secretary': 'escritoire',
'hypocrite': 'phony',
'innkeeper': 'host',
'helicopter': 'chopper',
'Altogether': 'entirely',
'mum': 'silent',
'athlete': 'jock',
'individual': 'person',
'bathtub': 'tub',
'investigator': 'researcher',
'intersection': 'overlap',
'delegates': 'assign',
'gentleman': 'valet',
'candidate': 'prospect',
'addict': 'hook',
'Trouble': 'worry',
'synagogue': 'temple',
'refrigerator': 'icebox',
'bowl': 'bowlful',
'genius': 'wizardry',
'stick': 'cling',
'accused': 'charge',
'interpreter': 'representative',
'boots': 'kick',
'sisters': 'sister',
'fellow': 'mate',
'trifles': 'triviality',
'boxes': 'corner',
'clock': 'time',
'paratrooper': 'para',
'doorbell': 'bell',
'butcher': 'slaughter',
'jail': 'imprison',
'lights': 'dismount',
'slob': 'sloven',
'brothers': 'buddy',
'couch': 'sofa',
'grandmother': 'granny',
'apron': 'proscenium',
'teahouse': 'teashop',
'hairdresser': 'hairstylist',
'sculpture': 'carving',
'handkerchief': 'hankie',
'homes': 'plate',
'fabric': 'framework',
'set': 'typeset',
'ballerina': 'danseuse',
'guest': 'node',
'robot': 'automaton',
'idiot': 'imbecile',
'inventor': 'discoverer',
'jeep': 'landrover',
'Cats': 'vomit',
'suitcase': 'bag',
'store': 'storehouse',
'pants': 'trouser',
'governor': 'regulator',
'rings': 'surround',
'tower': 'column',
'madman': 'maniac',
'intruder': 'interloper',
'surveys': 'view',
'theodolite': 'transit',
'bags': 'udder',
'pupil': 'student',
'Someone': 'person',
'cyclist': 'bicyclist',
'spectacles': 'glasses',
'splinter': 'sliver',
'dramatist': 'playwright',
'mailbox': 'postbox',
'server': 'waiter',
'tobacco': 'baccy',
'fireman': 'stoker',
'rubbers': 'rubberize',
'archer': 'sagittarius',
'Turtles': 'turtleneck',
'lab': 'laboratory',
'militant': 'activist',
'apartment': 'flat',
'braces': 'stimulate',
'Jump': 'start',
'astronaut': 'spaceman',
'package': 'software',
'photo': 'photograph',
'convertible': 'transformable',
'classroom': 'schoolroom',
'napkin': 'serviette',
'hamper': 'shackle',
'switch': 'trade',
'compasses': 'range',
'stairs': 'steps',
'pockets': 'scoop',
'rope': 'leash',
'photos': 'photograph',
'slacks': 'slump',
'henhouse': 'coop',
'den': 'lair',
'fireplace': 'hearth',
'flashlight': 'torch',
'donuts': 'doughnut',
'balls': 'testicle',
'frames': 'skeleton',
'poster': 'notice',
'cinema': 'film',
'tomb': 'grave',
'stadium': 'bowl',
'matches': 'oppose',
'biro': 'ballpoint',
'dagger': 'obelisk',
'sink': 'slump',
'counter': 'comeback',
'headphones': 'earphone',
'parcel': 'tract',
'whisk': 'whip',
'bookstore': 'bookshop',
'envelope': 'gasbag',
'exit': 'passing',
'bases': 'stem',
'horn': 'tusk',
'attic': 'loft',
'offices': 'position',
'pipeline': 'line',
'pens': 'write',
'pieces': 'piece',
'paintings': 'painting',
'backpack': 'pack',
'pavement': 'sidewalk',
'dresses': 'trim',
'blinds': 'subterfuge',
'belts': 'swath',
'pictures': 'characterization',
'blades': 'sword',
'violin': 'fiddle',

######################################
'tennis':'behavior',
'game':'smack',
'response':'game',
'ride':'competitions',
'election':'sitting',
'rugby':'step',
'elections':'business',
'darts':'penalty',
'suicide':'failure',
'production':'coup',
'soccer':'risks',
'training':'draw',
'sitting':'failure',
'post':'swimming',
'shopping':'fight',
'golf':'knitting',
'jazz':'fishing',
'robbery':'production',
'risks':'sports',
'hockey':'robbery',
'baseball':'business',
'chess':'ambulance',
'pushups':'step',
'snowing':'efforts',
'watching':'rush',
'spitting':'hockey',
'step':'sports',
'mercy':'playing',
'murder':'rush',
'shot':'battle',
'somersault':'playing',
'championships':'Literature',
'conflict':'duty',
'goals':'skiing',
'responsibility':'production',
'volleyball':'service',
'setbacks':'fishing',
'auction':'jump',
'action':'errors',
'smoking':'chastity',
'survey':'farming',
'errors':'linguistics',
'smack':'selling',
'resuscitation':'shot',
'skiing':'jump',
'competitions':'votes',
'match':'balcony',
'experiment':'snowing',
'Prostitution':'weight',
'massage':'destruction',
'votes':'kidnapping',
'knitting':'socializing',
'trafficking':'shopping',
'negligence':'spitting',
'weight':'trade',
'fishing':'fault',
'Skateboarding':'misconduct',
'disco':'seatbelt',
'performance':'offer',
'landings':'Registration',
'takeout':'massage',
'instruments':'conundrum',
'business':'racket',
'karaoke':'race',
'playing':'snowing',
'Registration':'race',
'failure':'work',
'dieting':'spinach',
'sacrifice':'mercy',
'referendum':'weight',
'spinach':'destruction',
'judo':'somersault',
'swimming':'spinach',
'dancing':'socializing',
'crime':'karaoke',
'butterfly':'frogs',
'koala':'locust',
'ants':'crocodile',
'horse':'ticks',
'eggs':'bread',
'lamb':'butterfly',
'wolf':'lions',
'gulls':'dolphin',
'donkeys':'carp',
'toys':'switch',
'silkworm':'wolves',
'lizards':'parrot',
'gorilla':'insect',
'sheep':'snake',
'cats':'reptiles',
'snake':'ticks',
'tiger':'fox',
'dolphin':'hog',
'spiders':'squirrel',
'pigeon':'cricket',
'duck':'fleas',
'peacock':'goat',
'whale':'lizards',
'androids':'locust',
'frog':'tiger',
'alligator':'spider',
'bee':'chickens',
'fox':'Dinosaurs',
'pig':'dog',
'deer':'pony',
'egg':'coffees',
'hare':'bears',
'cubs':'turtles',
'chicken':'jackal',
'wings':'wolves',
'lion':'peacock',
'locust':'lion',
'birds':'animals',
'rat':'elephants',
'animals':'swan',
'flies':'bull',
'parrot':'piggy',
'spider':'goat',
'giraffes':'pigs',
'lobsters':'cock',
'mosquitoes':'bat',
'ping':'bird',
'elephants':'pandas',
'lemur':'parrot',
'penguin':'bat',
'grasshoppers':'cats',
'foxes':'cubs',
'Dinosaurs':'flies',
'rabbits':'dog',
'caterpillar':'hedgehog',
'snakes':'bats',
'goat':'badger',
'grasshopper':'human',
'crocodile':'duck',
'shark':'human',
'feathers':'eel',
'wasps':'frogs',
'stags':'turtles',
'Sharks':'androids',
'bat':'suitcases',
'pony':'hornet',
'giraffe':'androids',
'cricket':'worms',
'jackal':'hare',
'crows':'pig',
'lions':'fox',
'elephant':'hedgehog',
'frogs':'insects',
'trout':'birds',
'eel':'sheep',
'ponies':'Dinosaurs',
'goose':'goat',
'ticks':'pig',
'mice':'bats',
'human':'butterflies',
'shellfish':'Sharks',
'hog':'horse',
'tomcat':'fleas',
'fly':'grasshopper',
'bats':'ping',
'donkey':'wasp',
'tail':'cubs',
'swan':'bear',
'tortoise':'nuts',
'reptiles':'nuts',
'pandas':'tomcat',
'hornet':'grasshopper',
'fleas':'nuts',
'horses':'locust',
'car':'shop',
'card':'ceiling',
'truck':'apartment',
'kite':'installation',
'floor':'goggles',
'hat':'crossbow',
'gown':'airport',
'silk':'intersection',
'boat':'spectacles',
'bench':'pets',
'street':'hearse',
'balloon':'collar',
'buses':'boots',
'headquarters':'bucket',
'thermometer':'watch',
'target':'horn',
'house':'flag',
'toy':'door',
'cable':'blinds',
'fridge':'cowboy hat',
'garden':'public',
'bus':'socks',
'mic':'box',
'camera':'umbrella',
'road':'brushes',
'elevator':'tape',
'bed':'landing',
'thread':'toy',
'hotel':'elevator',
'penicillin':'whisk',
'shorts':'watch',
'roof':'violin',
'lamp':'cakes',
'ceiling':'fabric',
'building':'laptop',
'canoe':'cell',
'cars':'thermometer',
'plates':'dishwasher',
'restaurant':'dress',
'tines':'hearse',
'fork':'seek',
'hut':'purse',
'shoes':'church',
'doll':'wallet',
'ambulance':'radio',
'sunglasses':'market',
'bag':'museum',
'ball':'buses',
'hospital':'cell',
'flag':'houses',
'rifle':'bullet',
'cage':'candle',
'museum':'airport',
'flute':'plate',
'sedative':'croutons',
'balcony':'prison',
'cigarette':'bag',
'lighter':'bassoon',
'keyboard':'bedroom',
'hammer':'seek',
'map':'sword',
'Masterpieces':'balls',
'theater':'safe',
'harp':'planes',
'squash':'blackboard',
'fence':'clubhouse',
'kimono':'telegraph',
'shirt':'installation',
'computer':'drums',
'lightbulb':'mic',
'seats':'ventilator',
'plane':'telephone',
'closet':'supermarket',
'toaster':'exit',
'jeans':'seek',
'radio':'video',
'newspapers':'card',
'heel':'cab',
'ship':'blankets',
'anchor':'spiders',
'mosques':'collar',
'tie':'radio',
'tent':'plates',
'bucket':'rooms',
'drums':'exit',
'organ':'gloves',
'teapot':'phones',
'yard':'hut',
'toilet':'seatbelt',
'station':'cap',
'jacket':'hammer',
'bell':'counter',
'gun':'guitar',
'gate':'compasses',
'prison':'hamper',
'legos':'eyeglasses',
'costume':'package',
'haircut':'parking',
'bridge':'towel',
'guitar':'teahouse',
'jet':'ball',
'concerts':'Esperanto',
'painting':'dolls',
'masterpiece':'pen',
'drugs':'rings',
'stand':'supermarket',
'condoms':'museums',
'kitchen':'aquarium',
'lipstick':'net',
'goggles':'roses',
'villa':'Candles',
'embassy':'goggles',
'statue':'rooms',
'office':'suit',
'pool':'business',
'spear':'bracelet',
'TV':'joke',
'towel':'siren',
'tyres':'sweatshirt',
'umbrella':'landing',
'tape':'grave',
'VCR':'dresses',
'market':'medicine',
'dimples':'cups',
'suitcases':'library',
'trains':'lipstick',
'tunnel':'chopsticks',
'restroom':'bicycle',
'bookstores':'belts',
'can':'dams',
'ammunition':'comedies',
'candle':'cellar',
'accordion':'map',
'birdcage':'bottles',
'ventilator':'teahouse',
'mobile':'cart',
'flight':'biro',
'wing':'grave',
'sweatshirt':'refrigerator',
'briefcase':'houses',
'corner':'garden',
'pencil':'vanilla',
'tires':'public',
'cathedral':'luggage',
'planes':'mat',
'net':'refrigerator',
'mug':'cigars',
'pills':'planetarium',
'antibiotics':'pills',
'ladybug':'table',
'coffin':'back',
'hearse':'public',
'tanker':'airport',
'cowboy hat':'baggage',
'shelves':'train',
'trap':'shirt',
'suit':'vehicle',
'scythe':'defibrillator',
'cigar':'horn',
'zipper':'ceiling',
'bombs':'tires',
'collar':'ring',
'opera':'cartoons',
'trombone':'store',
'covers':'chairs',
'handkerchiefs':'knives',
'spoon':'dimples',
'landing':'gown',
'toothpick':'planetarium',
'torch':'raft',
'spoonfuls':'base',
'cafeteria':'fork',
'university':'candle',
'rink':'shirts',
'cartwheel':'wheelchairs',
'safe':'haircut',
'laptop':'flute',
'tux':'attic',
'dolls':'seek',
'microscope':'submarine',
'ATM':'heel',
'clubhouse':'villa',
'farm':'supermarket',
'pillows':'jail',
'clarinet':'knife',
'button':'apartment',
'gloves':'boots',
'defibrillator':'bucket',
'bridges':'purse',
'squirrel':'envelope',
'shirts':'cart',
'cart':'squirrel',
'shed':'alarm',
'fingerprints':'trifles',
'pets':'shipwreck',
'laundry':'masterpiece',
'wagons':'school',
'tools':'pets',
'vehicle':'pipe',
'garage':'button',
'racket':'cellar',
'seatbelt':'birdcage',
'saw':'cradle',
'shelf':'store',
'balloons':'shed',
'dam':'key',
'volcanoes':'cellar',
'towels':'wallet',
'cradle':'table',
'belt':'ax',
'bedroom':'heroin',
'blanket':'accordion',
'palace':'zoo',
'shipwreck':'mosques',
'eyeglasses':'boats',
'screwdriver':'shipwreck',
'blankets':'boxes',
'viagra':'business',
'washing':'flight',
'boats':'den',
'key':'hall',
'plate':'rooms',
'toothbrush':'fabric',
'factories':'base',
'sulfa':'pencil',
'raft':'buildings',
'bulb':'sulfa',
'radar':'wool',
'lifeboats':'cafeteria',
'film':'visa',
'pipe':'gate',
'stamp':'answers',
'machines':'card',
'cocaine':'landing',
'helmet':'rubbers',
'oboe':'grave',
'crossbow':'doorbell',
'magazine':'visa',
'cellphone':'houses',
'trigger':'costume',
'bulbs':'room',
'basket':'bottle',
'pencils':'pens',
'oryx':'elevator',
'tables':'shorts',
'atlas':'drug',
'machine':'fence',
'heroin':'hotel',
'vanilla':'walnuts',
'embankment':'seat',
'mattress':'slacks',
'tube':'jeep',
'arrow':'pool',
'baggage':'closet',
'artifacts':'wagons',
'dishwasher':'TV',
'warehouse':'counter',
'ranch':'bullet',
'timer':'boat',
'tire':'mosque',
'telegraph':'planetarium',
'siren':'spoonfuls',
'brushes':'truck',
'stores':'clock',
'wheelchairs':'jacket',
'lock':'disco',
'mosque':'ambulance',
'railroad':'bar',
'pin':'dentist',
'chairs':'tires',
'saltshaker':'target',
'cigars':'mailbox',
'folder':'train',
'overcoat':'warehouse',
'cell':'ferry',
'highway':'tanker',
'cellar':'mic',
'backyard':'thread',
'saw mill':'suit',
'submarine':'miniature',
'vase':'hotels',
'valet':'doll',
'parking':'bar',
'system':'bridges',
'bassoon':'corner',
'supermarket':'cafeteria',
'museums':'zoo',
'ferry':'bedroom',
'carpet':'library',
'mat':'pockets',
'saxophone':'tower',
'aquarium':'tie',
'passageway':'safe',
'planetarium':'floor',
'comedies':'theater',
'rocket':'dishwasher',
'pot':'jar',
'installation':'ball',
'cocktail':'clothes',
'miniature':'engraving',
'church':'drug',
'flagship':'toothbrush',
'snowboard':'safe',
'engraving':'chairs',
'hotels':'fingerprints',
'oven':'arms',
'dams':'mobile',
'dikes':'lamp',
'pickup':'tent',
'triceps':'parcel',
'pillow':'dentist',
'video':'root',
'capacity':'power',
'temperature':'number',
'way':'hometown',
'instrument':'perspiration',
'red':'mould',
'manners':'perspiration',
'heat':'constipation',
'power':'brown',
'price':'capacity',
'taste':'price',
'complexion':'capacity',
'brown':'red',
'personality':'power',
'age':'red',
'throat':'nails',
'nose':'feet',
'stomach':'fist',
'face':'vagina',
'arms':'dick',
'mouth':'penis',
'shoulder':'shoulders',
'head':'paramedics',
'tooth':'foot',
'back':'eyelashes',
'sleeve':'chest',
'eyes':'eye',
'appendix':'tongue',
'ankle':'fist',
'nails':'fingernails',
'blood':'brows',
'feet':'kilometers',
'biceps':'wrist',
'leg':'finger',
'bone':'brows',
'hands':'palm',
'toes':'head',
'vagina':'shoulders',
'tears':'eyes',
'beard':'gums',
'forehead':'joints',
'neck':'fingernails',
'fingers':'cheeks',
'fingertip':'temples',
'finger':'eyelashes',
'brows':'mouth',
'rib':'tears',
'toe':'fingernails',
'shoulders':'ear',
'fingernails':'feet',
'brain':'feet',
'chin':'shoulders',
'skull':'tear',
'bones':'fingers',
'joints':'legs',
'pocket':'eyes',
'tongue':'pussy',
'mole':'nose',
'tear':'hand',
'knees':'vagina',
'fist':'shoulder',
'temples':'mole',
'mustache':'penis',
'palm':'finger',
'nosebleed':'temples',
'theory':'linguistics',
'plot':'ideas',
'rules':'economics',
'test':'shake',
'economics':'obstacles',
'psychology':'chemistry',
'thought':'theory',
'goal':'ability',
'neurons':'math',
'chemistry':'ping pong',
'obstacles':'economics',
'mathematics':'mystery',
'mystery':'math',
'relativity':'ability',
'ping pong':'mystery',
'speakers':'sentences',
'Name':'records',
'poem':'newspaper',
'results':'magazines',
'ad':'tickets',
'medals':'honks',
'cartoons':'typos',
'song':'joke',
'diary':'television',
'surname':'report',
'DNA test':'play',
'goodbye':'comedy',
'ballot':'words',
'jokes':'letters',
'Esperanto':'congratulations',
'call':'return',
'play':'lullaby',
'spelling':'license',
'eyelashes':'initials',
'quacks':'letter',
'remarks':'postcards',
'secrets':'Literature',
'words':'subject',
'rule':'Name',
'tunes':'voice',
'letter':'fact',
'abbreviation':'congratulations',
'story':'line',
'list':'conversation',
'textbook':'points',
'songs':'TV',
'complaints':'history',
'tickets':'television',
'letters':'song',
'croutons':'speech',
'fact':'quacks',
'explanation':'reply',
'poems':'return',
'word':'Esperanto',
'album':'subject',
'bill':'diary',
'file':'talk',
'tattoo':'call',
'waltz':'chatter',
'puzzle':'sentences',
'symphonies':'jokes',
'concert':'document',
'encyclopedia':'reply',
'moralism':'alarm',
'visa':'overture',
'sign':'excuse',
'title':'speech',
'authority':'croutons',
'magazines':'ID',
'television':'talk',
'history':'smile',
'speech':'shake',
'invitation':'bass',
'tune':'mails',
'laws':'nonsense',
'return':'comments',
'ticket':'joke',
'sentences':'poems',
'joking':'syllable',
'lie':'notebook',
'Literature':'Scream',
'documents':'results',
'chapters':'newspaper',
'licence':'medal',
'answer':'points',
'initials':'laws',
'page':'syllable',
'numbers':'novel',
'Dinner':'visa',
'criticism':'reply',
'text':'album',
'misunderstanding':'title',
'notebooks':'award',
'opinion':'tunes',
'notebook':'postcards',
'novels':'Scream',
'quids':'reply',
'notes':'treaty',
'puzzles':'document',
'syllable':'ID',
'answers':'opera',
'specification':'goodbye',
'note':'overture',
'shake':'invitation',
'ID':'medley',
'points':'dictionary',
'voice':'overture',
'smile':'tattoo',
'lies':'language',
'conversation':'opinion',
'CDs':'rock',
'bass':'document',
'postcards':'television',
'lullaby':'list',
'lithographs':'fact',
'handwriting':'surname',
'document':'film',
'ignorance':'championships',
'start':'death',
'damage':'rock',
'emergency':'riot',
'whistle':'riot',
'times':'accidents',
'earthquake':'crash',
'tsunami':'earthquake',
'finals':'death',
'torture':'accident',
'accidents':'explosion',
'typhoon':'ceremony',
'hits':'festival',
'riot':'rock',
'explosion':'landslide',
'ceremony':'landslide',
'crash':'tsunami',
'tournament':'revolution',
'love':'anger',
'feelings':'hope',
'moods':'love',
'wasp':'envy',
'headache':'envy',
'melancholy':'moods',
'sincerity':'hope',
'dough':'toast',
'wine':'meals',
'mushrooms':'tea',
'sugar':'cereal',
'walnut':'candy',
'milk':'muffin',
'fish':'supper',
'food':'chestnuts',
'curry':'beer',
'pizza':'pints',
'teas':'ketchup',
'coffees':'peanuts',
'coffee':'salad',
'sandwich':'teas',
'cookie':'teas',
'gin':'honey',
'tonic':'banana',
'chocolates':'cookie',
'chestnuts':'cheese',
'beer':'mango',
'breakfast':'onions',
'dinner':'cereal',
'marshmallows':'oranges',
'meal':'strawberries',
'soup':'berries',
'soya':'onions',
'pie':'pilaf',
'popcorn':'cereal',
'orange':'vegan',
'vegetables':'cookies',
'onions':'wine',
'bread':'dinner',
'cuisine':'egg',
'bananas':'raspberries',
'tea':'squid',
'champagne':'lemon',
'cheese':'caviar',
'sauce':'supper',
'lunch':'veggie',
'sausage':'pizza',
'pretzels':'rice',
'drink':'milk',
'meals':'strawberries',
'walnuts':'food',
'blackberries':'bananas',
'hamburgers':'walnuts',
'stew':'toast',
'juice':'cake',
'strawberries':'sandwich',
'pints':'chocolates',
'gobbles':'tapioca',
'ketchup':'carrots',
'cookies':'bread',
'corn':'pilaf',
'tapioca':'curry',
'pudding':'soya',
'supper':'sausage',
'honey':'pizza',
'picnics':'mushrooms',
'peanuts':'ice',
'caviar':'meat',
'chips':'biscuit',
'tuna':'orange',
'salad':'chocolates',
'pilaf':'lemon',
'butter':'snacks',
'potato':'champagne',
'sandwiches':'coffees',
'marmalade':'mushrooms',
'pasta':'hot',
'raspberries':'pretzels',
'mango':'pudding',
'kebabs':'meat',
'bacon':'berries',
'pear':'sausage',
'carrots':'beer',
'gum':'beer',
'vegan':'paella',
'lasagna':'extract',
'cream':'raspberries',
'paella':'soup',
'margarine':'beans',
'team':'troops',
'Lions':'football',
'people':'library',
'teams':'institution',
'group':'Delegates',
'school':'clubs',
'staff':'conference',
'police':'linguist',
'library':'schools',
'parties':'court',
'rainforest':'organization',
'population':'swarm',
'bunch':'cultures',
'party':'University',
'table':'library',
'band':'meeting',
'Warpaint':'marathon',
'Pepsi':'CIA',
'Eurofins':'Lions',
'kindergarten':'team',
'convention':'woods',
'company':'airline',
'BSN':'pair',
'schools':'dike',
'Beatles':'people',
'crew':'family',
'IMF':'swarm',
'law':'family',
'organization':'woods',
'CIA':'family',
'world':'water',
'Harvard':'cultures',
'services':'party',
'terrorists':'organization',
'cavalry':'Paralympics',
'queue':'forest',
'Paralympics':'countries',
'Everyone':'actors',
'airline':'NGO',
'congregation':'population',
'troops':'throng',
'GM':'Pepsi',
'high school':'cultures',
'football':'table',
'Traffic':'congregation',
'clubs':'cult',
'public':'conference',
'PASOK':'line',
'NGO':'IMF',
'society':'school',
'club':'BSN',
'rebels':'Beatles',
'countries':'crew',
'institution':'parties',
'score':'bottle',
'delegation':'community',
'line':'band',
'community':'culture',
'forest':'score',
'Yale':'elderly',
'University':'conference',
'marathon':'cavalry',
'Latvia':'pair',
'Hamburg':'rainforest',
'tigers':'company',
'south':'Althing',
'place':'campus',
'site':'selfish',
'park':'city',
'home':'air',
'presence':'Buffalo',
'west':'hometown',
'tip':'capital',
'land':'presence',
'buildings':'area',
'root':'carrot',
'port':'way',
'cities':'air',
'center':'Mahjong',
'lawn':'capital',
'states':'degrees',
'seat':'Iceland',
'Court':'Buffalo',
'hill':'pit',
'routes':'buildings',
'Danger':'city',
'Mahjong':'haunt',
'blocks':'Beverly',
'campus':'neighborhood',
'Zambia':'Farting',
'selfish':'lawn',
'Origin':'routes',
'Farting':'area',
'landline':'seat',
'capital':'way',
'Buffalo':'campus',
'degrees':'percent',
'Alexandria':'ground',
'Iceland':'Danger',
'Althing':'selfish',
'Beverly':'soldiers',
'hometown':'Mahjong',
'jungle':'south',
'horizon':'seat',
'space':'Althing',
'ground':'pond',
'bedside':'place',
'Hydration':'neighborhood',
'conscience':'nature',
'nature':'river',
'island':'bank',
'lake':'island',
'sea':'stone',
'shore':'sky',
'stone':'poison',
'hole':'islands',
'river':'stream',
'volcano':'lake',
'rock':'coast',
'continent':'canal',
'stars':'sea',
'universe':'shore',
'mountain':'bank',
'globe':'star',
'fire':'plank',
'riverbed':'metres',
'islands':'lake',
'coral':'Europe',
'reef':'ocean',
'moon':'Everest',
'Everest':'Europe',
'mountains':'globe',
'seas':'Europe',
'canal':'river',
'coast':'reef',
'web':'nature',
'sky':'star',
'Africa':'lake',
'rivers':'stream',
'water':'stone',
'beach':'islands',
'Europe':'river',
'holes':'Everest',
'star':'holes',
'Nile':'moon',
'neighbor':'pickpocket',
'cobbler':'composer',
'persons':'man',
'girls':'Apple',
'Americans':'actors',
'tourists':'coach',
'tourist':'Experts',
'Everybody':'strangers',
'uncle':'student',
'girlfriend':'prisoner',
'doctors':'brothers',
'children':'doctor',
'ranger':'Suck',
'sister':'God',
'stranger':'fireman',
'nitpicker':'girl',
'politician':'policeman',
'player':'tourists',
'woodcutter':'prince',
'Reemtsma':'rangers',
'prince':'sailors',
'hostages':'acquaintance',
'nurse':'brutes',
'artists':'goblins',
'strangers':'actor',
'ex':'Beverly',
'soldier':'cyclist',
'author':'paratrooper',
'coach':'president',
'Nobody':'waitress',
'captain':'teacher',
'witch':'enemy',
'millionaires':'nitpicker',
'chef':'dowser',
'Cookie':'dramatist',
'grandfather':'milkman',
'idiots':'baby',
'child':'athlete',
'alderman':'chairman',
'inhabitants':'aunt',
'salesmen':'hero',
'Suck':'linguist',
'artist':'daughter',
'suspect':'Somebody',
'passengers':'aunt',
'Rudolf':'witch',
'member':'police',
'Terrorists':'host',
'freak':'witness',
'musician':'kidnappers',
'philosopher':'marine',
'cousin':'child',
'policemen':'baby',
'singer':'kisser',
'Men':'chief',
'wife':'Suck',
'maid':'prince',
'nephew':'son',
'explorer':'sons',
'demonstrators':'chairperson',
'predecessor':'artists',
'writer':'cheerleaders',
'teacher':'customers',
'psychiatrist':'boys',
'surgeon':'millionaires',
'patient':'philosopher',
'girl':'schoolgirl',
'lady':'paramedics',
'carpenter':'witch',
'director':'girlfriends',
'dancer':'soldier',
'mayor':'astronauts',
'traveller':'friend',
'person':'chief',
'students':'dramatist',
'driver':'piper',
'son':'patients',
'widow':'freak',
'robber':'husband',
'witness':'carpenter',
'president':'individual',
'greengrocer':'criminal',
'customers':'cowards',
'retard':'Men',
'kitten':'intruder',
'lesbian':'schoolgirl',
'comedian':'acquaintance',
'burglar':'Apple',
'beggars':'driver',
'Parmalat':'cousin',
'pirates':'brother',
'musicians':'prisoners',
'nieces':'surgeon',
'dentist':'lesbians',
'millionaire':'friends',
'kid':'Americans',
'leader':'travelers',
'dowser':'intruder',
'guy':'alderman',
'poet':'Bach',
'pickpocket':'schoolgirl',
'composer':'butcher',
'kidnappers':'hippo',
'workaholic':'aunt',
'kisser':'explorer',
'roommate':'diplomats',
'refugees':'conductor',
'Anybody':'president',
'aunt':'waitress',
'organizers':'millionaire',
'visitors':'astronaut',
'drivers':'God',
'camper':'coworker',
'journalist':'Yumi',
'lovers':'retard',
'boyfriend':'Experts',
'piper':'student',
'priest':'teacher',
'Gangsters':'Monopoly',
'shearer':'Reemtsma',
'pilot':'uncle',
'cheerleaders':'guests',
'diplomat':'Hanako',
'schoolgirl':'person',
'skaters':'police',
'optimist':'arsonist',
'morons':'children',
'Chabrol':'paramedics',
'Catherine':'cowards',
'players':'patients',
'criminals':'paramedics',
'heroine':'collectors',
'skier':'chairperson',
'soldiers':'daughters',
'daughters':'driver',
'boss':'guard',
'Swallows':'Schubert',
'lesbians':'mayor',
'deceased':'athletes',
'Experts':'idiot',
'private':'refugees',
'kids':'criminals',
'Monopoly':'painter',
'fool':'parents',
'printer':'Rudolf',
'coworker':'runner',
'alcoholic':'primaries',
'wives':'Somebody',
'knockout':'boys',
'rangers':'coworker',
'conductor':'Hitler',
'teachers':'girlfriends',
'miller':'pirates',
'psychologist':'nieces',
'ladies':'nurse',
'receptionist':'calculator',
'sons':'teacher',
'athletes':'Someone',
'actress':'slob',
'granddaughter':'Beverly',
'programmer':'survivors',
'diplomats':'militant',
'patients':'workaholic',
'great':'nurse',
'twins':'great',
'rich':'merchant',
'chauffeur':'manager',
'politics':'cook',
'collectors':'person',
'survivors':'girlfriend',
'runner':'travelers',
'pianist':'father',
'stuntman':'hairdresser',
'Yumi':'Everybody',
'neighbors':'skier',
'neighbour':'Grace',
'actors':'calculator',
'engineer':'Cookie',
'Thieves':'doctor',
'prisoners':'greengrocer',
'primaries':'parents',
'waitress':'guests',
'convict':'neighbor',
'shepherdess':'millionaires',
'designer':'actor',
'Apple':'poet',
'baker':'Senator',
'Meyer':'student',
'vice':'deceased',
'Englishman':'thief',
'goblins':'delegates',
'sailors':'server',
'newcomers':'milkman',
'mothers':'intruder',
'Islam':'surgeon',
'hero':'priest',
'monster':'Englishman',
'mugger':'waitress',
'tournaments':'Hanako',
'astronauts':'police',
'novelist':'cook',
'guard':'diplomat',
'vegetarian':'millionaire',
'cowards':'kid',
'executive':'fans',
'deities':'pirates',
'professor':'travelers',
'neurosurgeon':'criminal',
'Hitler':'suspect',
'Takeo':'primaries',
'travelers':'kidnappers',
'agent':'husband',
'mama':'addict',
'calculator':'Parmalat',
'Emperor':'guy',
'Bach':'primaries',
'host':'programmer',
'Senator':'parents',
'Offspring':'parents',
'painter':'guardian',
'Schubert':'thief',
'Muskrats':'host',
'Hanako':'Americans',
'God':'bully',
'Grace':'stranger',
'milkman':'Someone',
'physicist':'athlete',
'weather':'rays',
'rain':'winds',
'lightning':'winds',
'rays':'weather',
'death':'hours',
'hot':'lightning',
'raindrop':'effect',
'leaves':'wheat',
'tree':'branches',
'pollen':'mould',
'pansies':'trunk',
'trunk':'nuts',
'potatoes':'eucalyptus',
'apple':'flower',
'oranges':'cherry',
'trees':'nut',
'beetroot':'nuts',
'roses':'bamboo',
'birch':'branches',
'carrot':'flower',
'thorns':'fruit',
'Sunflowers':'fruit',
'fruit':'trees',
'banana':'oranges',
'wheat':'thorns',
'hazelnuts':'rice',
'Pineapple':'oranges',
'daisy':'trees',
'seeds':'daisy',
'nuts':'branches',
'weed':'pansies',
'tomatoes':'peppers',
'eucalyptus':'seeds',
'bamboo':'branches',
'rice':'flower',
'cherry':'oranges',
'bark':'hazelnuts',
'grass':'flowers',
'credit':'checks',
'money':'raise',
'income':'rent',
'fine':'tax',
'loss':'yen',
'dollars':'More',
'prices':'cash',
'fares':'counterfeit',
'diamond':'credit',
'revenues':'cash',
'pesos':'bottles',
'present':'benefits',
'yen':'dollar',
'debts':'expenses',
'cash':'jewels',
'currency':'expenditure',
'bronze':'coin',
'debt':'yen',
'jewels':'fortune',
'expenses':'prices',
'gifts':'fares',
'estate':'ring',
'winning':'rent',
'living':'wallet',
'purse':'jewels',
'benefits':'income',
'tax':'lottery',
'smoke':'flames',
'evolution':'warming',
'flames':'smoke',
'reaction':'smoke',
'warming':'fire',
'pounds':'cup',
'nothing':'cup',
'four':'slice',
'Thousands':'cup',
'miles':'pesos',
'six':'mile',
'meters':'four',
'million':'box',
'kilometers':'feet',
'dozen':'euros',
'quarter':'century',
'Three':'tons',
'Many':'kilograms',
'seven':'bottles',
'millions':'Eleven',
'cup':'tenth',
'nine':'six',
'cups':'billion',
'eight':'dollars',
'None':'four',
'Two':'number',
'cents':'euro',
'mile':'bottle',
'kilograms':'grams',
'euros':'ounce',
'five':'lots',
'bottles':'dozen',
'tenth':'slice',
'slice':'number',
'ten':'centimeters',
'grams':'bottles',
'ounce':'loads',
'half':'seven',
'More':'glass',
'stories':'grams',
'glass':'steel',
'dollar':'Many',
'euro':'More',
'Eleven':'stories',
'centimeters':'number',
'meter':'None',
'centigrade':'degrees',
'Marks':'ten',
'metric':'kilometers',
'room':'pounds',
'Fifteen':'More',
'bottle':'pesos',
'bucks':'centigrade',
'east':'percent',
'wrinkles':'circle',
'circle':'wrinkles',
'dot':'circle',
'championship':'Peace',
'scurvy':'constipation',
'war':'blackness',
'darkness':'dilemma',
'collapse':'allergy',
'cancer':'shadow',
'wealth':'behaviour',
'appendicitis':'danger',
'shade':'darkness',
'disease':'cold',
'symptoms':'death',
'behaviour':'symptoms',
'cold':'danger',
'slavery':'upset',
'osteoporosis':'wealth',
'claustrophobia':'constipation',
'alert':'shade',
'asthma':'blackness',
'insanity':'heat',
'bulimia':'ache',
'success':'appendicitis',
'Alzheimer':'situation',
'case':'problem',
'Peace':'doom',
'health':'shade',
'toothache':'appendicitis',
'chance':'pain',
'overcast':'doom',
'allergies':'toothache',
'allergy':'situation',
'latex':'Wednesday',
'shadow':'bulimia',
'upset':'insanity',
'blackness':'health',
'vacuum':'pain',
'noise':'overcast',
'pneumonia':'situation',
'situation':'allergies',
'unemployment':'pain',
'yarn':'iron',
'spaghetti':'snow',
'Trang':'cardboard',
'leather':'copper',
'Viscose':'puddle',
'Alcohol':'material',
'salt':'material',
'steel':'mineral',
'CD':'log',
'iron':'vinegar',
'snow':'gas',
'venom':'Cola',
'ironing':'abs',
'Coca':'mold',
'Cola':'ice',
'plank':'plastic',
'poison':'Trang',
'radium':'mold',
'hay':'water',
'rust':'mineral',
'dust':'spaghetti',
'Butter':'material',
'chemicals':'rust',
'Judy':'nitrogen',
'hydrogen':'trash',
'ink':'poop',
'Popocatepetl':'mud',
'sponge':'Trang',
'mineral':'gas',
'paper':'gas',
'mold':'coal',
'meat':'fire',
'rosé':'Butter',
'gas':'log',
'aspirin':'gluten',
'neon':'poop',
'argon':'ironing',
'xenon':'glass',
'gases':'wood',
'desk':'stone',
'ice':'paper',
'straw':'gases',
'mud':'gas',
'vinegar':'mold',
'copper':'clay',
'dynamite':'venom',
'cardboard':'hay',
'silver':'mould',
'protein':'iron',
'Grease':'ink',
'oxygen':'CD',
'nitrogen':'steel',
'abs':'leather',
'tin':'plank',
'gluten':'mineral',
'puddle':'hydrogen',
'colour':'leather',
'months':'Thursday',
'years':'sunrise',
'Monday':'midnight',
'yesterday':'Wednesday',
'May':'future',
'days':'midday',
'June':'century',
'September':'dream',
'day':'latex',
'August':'vacation',
'January':'moment',
'July':'May',
'hour':'Wednesday',
'Fahrenheit':'summer',
'time':'century',
'moment':'vacation',
'middle':'curfew',
'hours':'dream',
'Today':'afternoon',
'summer':'latex',
'year':'curfew',
'doomsday':'weeks',
'midnight':'Today',
'Friday':'quarter',
'weeks':'hours',
'March':'Fahrenheit',
'deadline':'midnight',
'morning':'moons',
'afternoon':'November',
'night':'year',
'dawn':'Monday',
'dusk':'summer',
'February':'week',
'November':'month',
'tomorrow':'February',
'Tuesday':'midday',
'seventies':'days',
'Winter':'century',
'December':'months',
'October':'doomsday',
'Saturday':'August',
'April':'megabytes',
'weekend':'months',
'dream':'dawn',
'second':'doomsday',
'month':'April',
'Thursday':'tomorrow',
'Olympics':'morning',
'sunrise':'hours',
'future':'years',
'Christmas':'seventies',
'megabytes':'May',
'Sunday':'days',
'curfew':'dream',
'object':'aliens'
}
with open('./gold-pmb-original/train-original.txt.raw') as main, open(
        'noun_augmentation_train_files/Text-noun-changed-outside-data_with_SS.txt', 'w') as done:
     text = main.read()
     done.write(re.sub(r'\b\w+\b', lambda x: word_list.get(x.group(), x.group()), text))